name: 🚀 Deploy to Hostinger via FTP

on:
  push:
    branches:
    - main # Se ejecuta cuando pusheas a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout del código
      uses: actions/checkout@v3

    - name: 📤 Deploy vía FTP a Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /home/u931942264/domains/csluduena.com/public_html/
